### ISSUE TITLE
training error ./scripts/train_image_object_detection.sh

### ISSUE THREAD

**Issue by youyingyin** [tidsp/caffe-jacinto-models#10]
I0611 00:04:31.663493  8740 net.cpp:403] Top memory (TEST) required for data: 1703675240 diff: 1703675240
I0611 00:04:31.663501  8740 net.cpp:406] Bottom memory (TEST) required for data: 1703674816 diff: 1703674816
I0611 00:04:31.663507  8740 net.cpp:409] Shared (in-place) memory (TEST) by data: 695552000 diff: 695552000
I0611 00:04:31.663511  8740 net.cpp:412] Parameters memory (TEST) required for data: 19132568 diff: 19132568
I0611 00:04:31.663516  8740 net.cpp:415] Parameters shared memory (TEST) by data: 0 diff: 0
I0611 00:04:31.663519  8740 net.cpp:421] Network initialization done.
F0611 00:04:31.663878  8740 io.cpp:55] Check failed: fd != -1 (-1 vs. -1) File not found: training/voc0712/JDetNet/20190611_00-04_ds_PSP_dsFac_32_hdDS8_1/sparse/voc0712_ssdJacintoNetV2_iter_120000.caffemodel
*** Check failure stack trace: ***
    @     0x7f6b599f75cd  google::LogMessage::Fail()
    @     0x7f6b599f9433  google::LogMessage::SendToLog()
    @     0x7f6b599f715b  google::LogMessage::Flush()
    @     0x7f6b599f9e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f6b5a5d84dc  caffe::ReadProtoFromBinaryFile()
    @     0x7f6b5a653de6  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7f6b5aa99dea  caffe::Net::CopyTrainedLayersFromBinaryProto()
    @     0x7f6b5aa99e8e  caffe::Net::CopyTrainedLayersFrom()
    @           0x41202c  test_detection()
    @           0x40d1d0  main
    @     0x7f6b58179830  __libc_start_main
    @           0x40de69  _start
    @              (nil)  (unknown)

**Comment by mathmanu** [comment]
Can you attach the full log file?

**Comment by mathmanu** [comment]
Closing, since there is no reply.
