### ISSUE TITLE
no module named propagate_obj 

### ISSUE THREAD

**Issue by youyingyin** [tidsp/caffe-jacinto-models#11]
ssd_detect_video.py

![Screenshot from 2019-06-12 21-12-49](https://user-images.githubusercontent.com/33154862/59354340-87b57c80-8d57-11e9-9cb7-eedc40899961.png)

**Comment by checko** [comment]
git checkout 6ca88ff12e559a839ae5ee9bc7c25201f0ed9217 scripts/propagate_obj.py
