### ISSUE TITLE
Hi, could you tell me the sparse method in segmetation?

### ISSUE THREAD

**Issue by deeptoby** [tidsp/caffe-jacinto-models#12]
i want to learn it and do some changes.

**Comment by mathmanu** [comment]
You can refer to the paper:
Sparse, Quantized, Full Frame CNN for Low Power Embedded Devices
Manu Mathew et. al., CVPR 2017
http://openaccess.thecvf.com/content_cvpr_2017_workshops/w4/papers/Mathew_Sparse_Quantized_Full_CVPR_2017_paper.pdf
